name: Gabrielle

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md" ]

  workflow_dispatch:

jobs:
  primeiro-job:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir RA - Nome
        run: echo "6324589 - Gabrielle Palma"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Lista os arquivos no diretório home
        run: ls ~